namespace Smartphone_Management.GUI
{
    partial class QuanLyNhaCungCap
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(QuanLyNhaCungCap));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.dtgNCC = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.txtSearchNCC = new Bunifu.UI.WinForms.BunifuTextBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.btnThemNCC = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnXoaNCC = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSuaNCC = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtDiaChi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.txtDienThoai = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.txtTenNCC = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.tableLayoutPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dtgNCC)).BeginInit();
            this.groupBox3.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.bunifuGroupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 1;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Controls.Add(this.dtgNCC, 0, 2);
            this.tableLayoutPanel1.Controls.Add(this.groupBox3, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.groupBox2, 0, 1);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Margin = new System.Windows.Forms.Padding(2);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 3;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 11.9403F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 35.10204F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 53.06123F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(811, 490);
            this.tableLayoutPanel1.TabIndex = 0;
            // 
            // dtgNCC
            // 
            this.dtgNCC.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(48)))), ((int)(((byte)(52)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.White;
            this.dtgNCC.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.dtgNCC.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dtgNCC.BackgroundColor = System.Drawing.Color.White;
            this.dtgNCC.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dtgNCC.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dtgNCC.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(63)))), ((int)(((byte)(65)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtgNCC.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.dtgNCC.ColumnHeadersHeight = 40;
            this.dtgNCC.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(48)))), ((int)(((byte)(52)))));
            this.dtgNCC.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtgNCC.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.White;
            this.dtgNCC.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            this.dtgNCC.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            this.dtgNCC.CurrentTheme.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.dtgNCC.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(56)))), ((int)(((byte)(62)))));
            this.dtgNCC.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.dtgNCC.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dtgNCC.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dtgNCC.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(63)))), ((int)(((byte)(65)))));
            this.dtgNCC.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dtgNCC.CurrentTheme.Name = null;
            this.dtgNCC.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(37)))), ((int)(((byte)(41)))));
            this.dtgNCC.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtgNCC.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.White;
            this.dtgNCC.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            this.dtgNCC.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(37)))), ((int)(((byte)(41)))));
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(117)))), ((int)(((byte)(119)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.WhiteSmoke;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dtgNCC.DefaultCellStyle = dataGridViewCellStyle6;
            this.dtgNCC.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dtgNCC.EnableHeadersVisualStyles = false;
            this.dtgNCC.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(56)))), ((int)(((byte)(62)))));
            this.dtgNCC.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(16)))), ((int)(((byte)(18)))));
            this.dtgNCC.HeaderBgColor = System.Drawing.Color.Empty;
            this.dtgNCC.HeaderForeColor = System.Drawing.Color.White;
            this.dtgNCC.Location = new System.Drawing.Point(3, 232);
            this.dtgNCC.MultiSelect = false;
            this.dtgNCC.Name = "dtgNCC";
            this.dtgNCC.ReadOnly = true;
            this.dtgNCC.RowHeadersVisible = false;
            this.dtgNCC.RowTemplate.Height = 40;
            this.dtgNCC.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dtgNCC.Size = new System.Drawing.Size(805, 255);
            this.dtgNCC.TabIndex = 0;
            this.dtgNCC.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Dark;
            this.dtgNCC.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtgNCC_CellContentClick);
            this.dtgNCC.CellMouseClick += new System.Windows.Forms.DataGridViewCellMouseEventHandler(this.dtgNCC_CellMouseClick);
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.label4);
            this.groupBox3.Controls.Add(this.txtSearchNCC);
            this.groupBox3.Location = new System.Drawing.Point(2, 2);
            this.groupBox3.Margin = new System.Windows.Forms.Padding(2);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Padding = new System.Windows.Forms.Padding(2);
            this.groupBox3.Size = new System.Drawing.Size(807, 54);
            this.groupBox3.TabIndex = 2;
            this.groupBox3.TabStop = false;
            // 
            // txtSearchNCC
            // 
            this.txtSearchNCC.AcceptsReturn = false;
            this.txtSearchNCC.AcceptsTab = false;
            this.txtSearchNCC.AnimationSpeed = 200;
            this.txtSearchNCC.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSearchNCC.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSearchNCC.BackColor = System.Drawing.Color.Transparent;
            this.txtSearchNCC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSearchNCC.BackgroundImage")));
            this.txtSearchNCC.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSearchNCC.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSearchNCC.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSearchNCC.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSearchNCC.BorderRadius = 32;
            this.txtSearchNCC.BorderThickness = 1;
            this.txtSearchNCC.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSearchNCC.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearchNCC.DefaultFont = new System.Drawing.Font("Arial Narrow", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSearchNCC.DefaultText = "";
            this.txtSearchNCC.FillColor = System.Drawing.Color.White;
            this.txtSearchNCC.HideSelection = true;
            this.txtSearchNCC.IconLeft = null;
            this.txtSearchNCC.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearchNCC.IconPadding = 10;
            this.txtSearchNCC.IconRight = null;
            this.txtSearchNCC.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearchNCC.Lines = new string[0];
            this.txtSearchNCC.Location = new System.Drawing.Point(4, 17);
            this.txtSearchNCC.Margin = new System.Windows.Forms.Padding(2);
            this.txtSearchNCC.MaxLength = 32767;
            this.txtSearchNCC.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSearchNCC.Modified = false;
            this.txtSearchNCC.Multiline = false;
            this.txtSearchNCC.Name = "txtSearchNCC";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearchNCC.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSearchNCC.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearchNCC.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearchNCC.OnIdleState = stateProperties20;
            this.txtSearchNCC.Padding = new System.Windows.Forms.Padding(2);
            this.txtSearchNCC.PasswordChar = '\0';
            this.txtSearchNCC.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSearchNCC.PlaceholderText = "Tìm kiếm";
            this.txtSearchNCC.ReadOnly = false;
            this.txtSearchNCC.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSearchNCC.SelectedText = "";
            this.txtSearchNCC.SelectionLength = 0;
            this.txtSearchNCC.SelectionStart = 0;
            this.txtSearchNCC.ShortcutsEnabled = true;
            this.txtSearchNCC.Size = new System.Drawing.Size(194, 32);
            this.txtSearchNCC.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSearchNCC.TabIndex = 32;
            this.txtSearchNCC.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSearchNCC.TextMarginBottom = 0;
            this.txtSearchNCC.TextMarginLeft = 3;
            this.txtSearchNCC.TextMarginTop = 0;
            this.txtSearchNCC.TextPlaceholder = "Tìm kiếm";
            this.txtSearchNCC.UseSystemPasswordChar = false;
            this.txtSearchNCC.WordWrap = true;
            this.txtSearchNCC.TextChange += new System.EventHandler(this.txtSearchNCC_TextChange);
            // 
            // groupBox2
            // 
            this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox2.Controls.Add(this.bunifuGroupBox1);
            this.groupBox2.Controls.Add(this.bunifuButton1);
            this.groupBox2.Controls.Add(this.txtDiaChi);
            this.groupBox2.Controls.Add(this.label2);
            this.groupBox2.Controls.Add(this.txtDienThoai);
            this.groupBox2.Controls.Add(this.label1);
            this.groupBox2.Controls.Add(this.txtTenNCC);
            this.groupBox2.Controls.Add(this.label3);
            this.groupBox2.ForeColor = System.Drawing.Color.Black;
            this.groupBox2.Location = new System.Drawing.Point(2, 60);
            this.groupBox2.Margin = new System.Windows.Forms.Padding(2);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Padding = new System.Windows.Forms.Padding(2);
            this.groupBox2.Size = new System.Drawing.Size(807, 167);
            this.groupBox2.TabIndex = 1;
            this.groupBox2.TabStop = false;
            this.groupBox2.UseCompatibleTextRendering = true;
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox1.BorderRadius = 1;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.btnThemNCC);
            this.bunifuGroupBox1.Controls.Add(this.btnXoaNCC);
            this.bunifuGroupBox1.Controls.Add(this.btnSuaNCC);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(483, 17);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(183, 144);
            this.bunifuGroupBox1.TabIndex = 50;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Chức năng";
            // 
            // btnThemNCC
            // 
            this.btnThemNCC.AllowAnimations = true;
            this.btnThemNCC.AllowMouseEffects = true;
            this.btnThemNCC.AllowToggling = false;
            this.btnThemNCC.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnThemNCC.AnimationSpeed = 200;
            this.btnThemNCC.AutoGenerateColors = false;
            this.btnThemNCC.AutoRoundBorders = false;
            this.btnThemNCC.AutoSizeLeftIcon = true;
            this.btnThemNCC.AutoSizeRightIcon = true;
            this.btnThemNCC.BackColor = System.Drawing.Color.Transparent;
            this.btnThemNCC.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            this.btnThemNCC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThemNCC.BackgroundImage")));
            this.btnThemNCC.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThemNCC.ButtonText = "Thêm";
            this.btnThemNCC.ButtonTextMarginLeft = 0;
            this.btnThemNCC.ColorContrastOnClick = 45;
            this.btnThemNCC.ColorContrastOnHover = 45;
            this.btnThemNCC.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnThemNCC.CustomizableEdges = borderEdges5;
            this.btnThemNCC.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThemNCC.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThemNCC.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThemNCC.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThemNCC.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnThemNCC.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnThemNCC.ForeColor = System.Drawing.Color.Black;
            this.btnThemNCC.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThemNCC.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnThemNCC.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnThemNCC.IconMarginLeft = 11;
            this.btnThemNCC.IconPadding = 10;
            this.btnThemNCC.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnThemNCC.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnThemNCC.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnThemNCC.IconSize = 25;
            this.btnThemNCC.IdleBorderColor = System.Drawing.Color.White;
            this.btnThemNCC.IdleBorderRadius = 1;
            this.btnThemNCC.IdleBorderThickness = 1;
            this.btnThemNCC.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            this.btnThemNCC.IdleIconLeftImage = global::Smartphone_Management.Properties.Resources.Add;
            this.btnThemNCC.IdleIconRightImage = null;
            this.btnThemNCC.IndicateFocus = false;
            this.btnThemNCC.Location = new System.Drawing.Point(6, 12);
            this.btnThemNCC.Name = "btnThemNCC";
            this.btnThemNCC.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThemNCC.OnDisabledState.BorderRadius = 1;
            this.btnThemNCC.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThemNCC.OnDisabledState.BorderThickness = 1;
            this.btnThemNCC.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThemNCC.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThemNCC.OnDisabledState.IconLeftImage = null;
            this.btnThemNCC.OnDisabledState.IconRightImage = null;
            this.btnThemNCC.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnThemNCC.onHoverState.BorderRadius = 1;
            this.btnThemNCC.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThemNCC.onHoverState.BorderThickness = 1;
            this.btnThemNCC.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnThemNCC.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnThemNCC.onHoverState.IconLeftImage = null;
            this.btnThemNCC.onHoverState.IconRightImage = null;
            this.btnThemNCC.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnThemNCC.OnIdleState.BorderRadius = 1;
            this.btnThemNCC.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThemNCC.OnIdleState.BorderThickness = 1;
            this.btnThemNCC.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(0)))));
            this.btnThemNCC.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnThemNCC.OnIdleState.IconLeftImage = global::Smartphone_Management.Properties.Resources.Add;
            this.btnThemNCC.OnIdleState.IconRightImage = null;
            this.btnThemNCC.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnThemNCC.OnPressedState.BorderRadius = 1;
            this.btnThemNCC.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThemNCC.OnPressedState.BorderThickness = 1;
            this.btnThemNCC.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnThemNCC.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnThemNCC.OnPressedState.IconLeftImage = null;
            this.btnThemNCC.OnPressedState.IconRightImage = null;
            this.btnThemNCC.Size = new System.Drawing.Size(99, 42);
            this.btnThemNCC.TabIndex = 49;
            this.btnThemNCC.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnThemNCC.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnThemNCC.TextMarginLeft = 0;
            this.btnThemNCC.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnThemNCC.UseDefaultRadiusAndThickness = true;
            this.btnThemNCC.Click += new System.EventHandler(this.btnThemNCC_Click);
            // 
            // btnXoaNCC
            // 
            this.btnXoaNCC.AllowAnimations = true;
            this.btnXoaNCC.AllowMouseEffects = true;
            this.btnXoaNCC.AllowToggling = false;
            this.btnXoaNCC.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnXoaNCC.AnimationSpeed = 200;
            this.btnXoaNCC.AutoGenerateColors = false;
            this.btnXoaNCC.AutoRoundBorders = false;
            this.btnXoaNCC.AutoSizeLeftIcon = true;
            this.btnXoaNCC.AutoSizeRightIcon = true;
            this.btnXoaNCC.BackColor = System.Drawing.Color.Transparent;
            this.btnXoaNCC.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(56)))), ((int)(((byte)(56)))));
            this.btnXoaNCC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnXoaNCC.BackgroundImage")));
            this.btnXoaNCC.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaNCC.ButtonText = "Xóa";
            this.btnXoaNCC.ButtonTextMarginLeft = 0;
            this.btnXoaNCC.ColorContrastOnClick = 45;
            this.btnXoaNCC.ColorContrastOnHover = 45;
            this.btnXoaNCC.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnXoaNCC.CustomizableEdges = borderEdges6;
            this.btnXoaNCC.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnXoaNCC.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXoaNCC.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXoaNCC.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXoaNCC.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnXoaNCC.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnXoaNCC.ForeColor = System.Drawing.Color.Black;
            this.btnXoaNCC.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnXoaNCC.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnXoaNCC.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnXoaNCC.IconMarginLeft = 11;
            this.btnXoaNCC.IconPadding = 10;
            this.btnXoaNCC.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnXoaNCC.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnXoaNCC.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnXoaNCC.IconSize = 25;
            this.btnXoaNCC.IdleBorderColor = System.Drawing.Color.White;
            this.btnXoaNCC.IdleBorderRadius = 1;
            this.btnXoaNCC.IdleBorderThickness = 1;
            this.btnXoaNCC.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(56)))), ((int)(((byte)(56)))));
            this.btnXoaNCC.IdleIconLeftImage = global::Smartphone_Management.Properties.Resources.Delete;
            this.btnXoaNCC.IdleIconRightImage = null;
            this.btnXoaNCC.IndicateFocus = false;
            this.btnXoaNCC.Location = new System.Drawing.Point(6, 109);
            this.btnXoaNCC.Name = "btnXoaNCC";
            this.btnXoaNCC.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXoaNCC.OnDisabledState.BorderRadius = 1;
            this.btnXoaNCC.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaNCC.OnDisabledState.BorderThickness = 1;
            this.btnXoaNCC.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXoaNCC.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXoaNCC.OnDisabledState.IconLeftImage = null;
            this.btnXoaNCC.OnDisabledState.IconRightImage = null;
            this.btnXoaNCC.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnXoaNCC.onHoverState.BorderRadius = 1;
            this.btnXoaNCC.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaNCC.onHoverState.BorderThickness = 1;
            this.btnXoaNCC.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnXoaNCC.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnXoaNCC.onHoverState.IconLeftImage = null;
            this.btnXoaNCC.onHoverState.IconRightImage = null;
            this.btnXoaNCC.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnXoaNCC.OnIdleState.BorderRadius = 1;
            this.btnXoaNCC.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaNCC.OnIdleState.BorderThickness = 1;
            this.btnXoaNCC.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(56)))), ((int)(((byte)(56)))));
            this.btnXoaNCC.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnXoaNCC.OnIdleState.IconLeftImage = global::Smartphone_Management.Properties.Resources.Delete;
            this.btnXoaNCC.OnIdleState.IconRightImage = null;
            this.btnXoaNCC.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXoaNCC.OnPressedState.BorderRadius = 1;
            this.btnXoaNCC.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoaNCC.OnPressedState.BorderThickness = 1;
            this.btnXoaNCC.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXoaNCC.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnXoaNCC.OnPressedState.IconLeftImage = null;
            this.btnXoaNCC.OnPressedState.IconRightImage = null;
            this.btnXoaNCC.Size = new System.Drawing.Size(99, 35);
            this.btnXoaNCC.TabIndex = 49;
            this.btnXoaNCC.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnXoaNCC.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnXoaNCC.TextMarginLeft = 0;
            this.btnXoaNCC.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnXoaNCC.UseDefaultRadiusAndThickness = true;
            this.btnXoaNCC.Click += new System.EventHandler(this.btnXoaNCC_Click);
            // 
            // btnSuaNCC
            // 
            this.btnSuaNCC.AllowAnimations = true;
            this.btnSuaNCC.AllowMouseEffects = true;
            this.btnSuaNCC.AllowToggling = false;
            this.btnSuaNCC.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnSuaNCC.AnimationSpeed = 200;
            this.btnSuaNCC.AutoGenerateColors = false;
            this.btnSuaNCC.AutoRoundBorders = false;
            this.btnSuaNCC.AutoSizeLeftIcon = true;
            this.btnSuaNCC.AutoSizeRightIcon = true;
            this.btnSuaNCC.BackColor = System.Drawing.Color.Transparent;
            this.btnSuaNCC.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(0)))));
            this.btnSuaNCC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSuaNCC.BackgroundImage")));
            this.btnSuaNCC.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSuaNCC.ButtonText = "Sửa";
            this.btnSuaNCC.ButtonTextMarginLeft = 0;
            this.btnSuaNCC.ColorContrastOnClick = 45;
            this.btnSuaNCC.ColorContrastOnHover = 45;
            this.btnSuaNCC.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnSuaNCC.CustomizableEdges = borderEdges7;
            this.btnSuaNCC.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSuaNCC.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSuaNCC.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSuaNCC.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSuaNCC.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSuaNCC.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSuaNCC.ForeColor = System.Drawing.Color.Black;
            this.btnSuaNCC.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSuaNCC.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSuaNCC.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSuaNCC.IconMarginLeft = 11;
            this.btnSuaNCC.IconPadding = 10;
            this.btnSuaNCC.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSuaNCC.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSuaNCC.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSuaNCC.IconSize = 25;
            this.btnSuaNCC.IdleBorderColor = System.Drawing.Color.White;
            this.btnSuaNCC.IdleBorderRadius = 1;
            this.btnSuaNCC.IdleBorderThickness = 1;
            this.btnSuaNCC.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(0)))));
            this.btnSuaNCC.IdleIconLeftImage = global::Smartphone_Management.Properties.Resources.fix;
            this.btnSuaNCC.IdleIconRightImage = null;
            this.btnSuaNCC.IndicateFocus = false;
            this.btnSuaNCC.Location = new System.Drawing.Point(6, 60);
            this.btnSuaNCC.Name = "btnSuaNCC";
            this.btnSuaNCC.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSuaNCC.OnDisabledState.BorderRadius = 1;
            this.btnSuaNCC.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSuaNCC.OnDisabledState.BorderThickness = 1;
            this.btnSuaNCC.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSuaNCC.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSuaNCC.OnDisabledState.IconLeftImage = null;
            this.btnSuaNCC.OnDisabledState.IconRightImage = null;
            this.btnSuaNCC.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSuaNCC.onHoverState.BorderRadius = 1;
            this.btnSuaNCC.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSuaNCC.onHoverState.BorderThickness = 1;
            this.btnSuaNCC.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSuaNCC.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSuaNCC.onHoverState.IconLeftImage = null;
            this.btnSuaNCC.onHoverState.IconRightImage = null;
            this.btnSuaNCC.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnSuaNCC.OnIdleState.BorderRadius = 1;
            this.btnSuaNCC.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSuaNCC.OnIdleState.BorderThickness = 1;
            this.btnSuaNCC.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(242)))), ((int)(((byte)(0)))));
            this.btnSuaNCC.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnSuaNCC.OnIdleState.IconLeftImage = global::Smartphone_Management.Properties.Resources.fix;
            this.btnSuaNCC.OnIdleState.IconRightImage = null;
            this.btnSuaNCC.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSuaNCC.OnPressedState.BorderRadius = 1;
            this.btnSuaNCC.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSuaNCC.OnPressedState.BorderThickness = 1;
            this.btnSuaNCC.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSuaNCC.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSuaNCC.OnPressedState.IconLeftImage = null;
            this.btnSuaNCC.OnPressedState.IconRightImage = null;
            this.btnSuaNCC.Size = new System.Drawing.Size(99, 43);
            this.btnSuaNCC.TabIndex = 49;
            this.btnSuaNCC.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSuaNCC.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSuaNCC.TextMarginLeft = 0;
            this.btnSuaNCC.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnSuaNCC.UseDefaultRadiusAndThickness = true;
            this.btnSuaNCC.Click += new System.EventHandler(this.btnSuaNCC_Click);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges8;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.White;
            this.bunifuButton1.IdleBorderRadius = 1;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton1.IdleIconLeftImage = global::Smartphone_Management.Properties.Resources.Refresh;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(10, 70);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnIdleState.IconLeftImage = global::Smartphone_Management.Properties.Resources.Refresh;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(53, 50);
            this.bunifuButton1.TabIndex = 49;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // txtDiaChi
            // 
            this.txtDiaChi.AcceptsReturn = false;
            this.txtDiaChi.AcceptsTab = false;
            this.txtDiaChi.AnimationSpeed = 200;
            this.txtDiaChi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDiaChi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDiaChi.BackColor = System.Drawing.Color.Transparent;
            this.txtDiaChi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDiaChi.BackgroundImage")));
            this.txtDiaChi.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDiaChi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDiaChi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDiaChi.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDiaChi.BorderRadius = 15;
            this.txtDiaChi.BorderThickness = 2;
            this.txtDiaChi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDiaChi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.DefaultFont = new System.Drawing.Font("Arial", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDiaChi.DefaultText = "";
            this.txtDiaChi.FillColor = System.Drawing.Color.White;
            this.txtDiaChi.ForeColor = System.Drawing.Color.LightSeaGreen;
            this.txtDiaChi.HideSelection = true;
            this.txtDiaChi.IconLeft = null;
            this.txtDiaChi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.IconPadding = 10;
            this.txtDiaChi.IconRight = null;
            this.txtDiaChi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDiaChi.Lines = new string[0];
            this.txtDiaChi.Location = new System.Drawing.Point(332, 34);
            this.txtDiaChi.Margin = new System.Windows.Forms.Padding(2);
            this.txtDiaChi.MaxLength = 32767;
            this.txtDiaChi.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDiaChi.Modified = false;
            this.txtDiaChi.Multiline = false;
            this.txtDiaChi.Name = "txtDiaChi";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDiaChi.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.LightSeaGreen;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDiaChi.OnIdleState = stateProperties24;
            this.txtDiaChi.Padding = new System.Windows.Forms.Padding(2);
            this.txtDiaChi.PasswordChar = '\0';
            this.txtDiaChi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDiaChi.PlaceholderText = "";
            this.txtDiaChi.ReadOnly = false;
            this.txtDiaChi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDiaChi.SelectedText = "";
            this.txtDiaChi.SelectionLength = 0;
            this.txtDiaChi.SelectionStart = 0;
            this.txtDiaChi.ShortcutsEnabled = true;
            this.txtDiaChi.Size = new System.Drawing.Size(132, 31);
            this.txtDiaChi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDiaChi.TabIndex = 43;
            this.txtDiaChi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDiaChi.TextMarginBottom = 0;
            this.txtDiaChi.TextMarginLeft = 3;
            this.txtDiaChi.TextMarginTop = 0;
            this.txtDiaChi.TextPlaceholder = "";
            this.txtDiaChi.UseSystemPasswordChar = false;
            this.txtDiaChi.WordWrap = true;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.Black;
            this.label2.Location = new System.Drawing.Point(338, 17);
            this.label2.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(49, 15);
            this.label2.TabIndex = 41;
            this.label2.Text = "Địa chỉ:";
            // 
            // txtDienThoai
            // 
            this.txtDienThoai.AcceptsReturn = false;
            this.txtDienThoai.AcceptsTab = false;
            this.txtDienThoai.AnimationSpeed = 200;
            this.txtDienThoai.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDienThoai.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDienThoai.BackColor = System.Drawing.Color.Transparent;
            this.txtDienThoai.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDienThoai.BackgroundImage")));
            this.txtDienThoai.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDienThoai.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDienThoai.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDienThoai.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDienThoai.BorderRadius = 15;
            this.txtDienThoai.BorderThickness = 2;
            this.txtDienThoai.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDienThoai.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDienThoai.DefaultFont = new System.Drawing.Font("Arial", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDienThoai.DefaultText = "";
            this.txtDienThoai.FillColor = System.Drawing.Color.White;
            this.txtDienThoai.ForeColor = System.Drawing.Color.LightSeaGreen;
            this.txtDienThoai.HideSelection = true;
            this.txtDienThoai.IconLeft = null;
            this.txtDienThoai.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDienThoai.IconPadding = 10;
            this.txtDienThoai.IconRight = null;
            this.txtDienThoai.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDienThoai.Lines = new string[0];
            this.txtDienThoai.Location = new System.Drawing.Point(177, 34);
            this.txtDienThoai.Margin = new System.Windows.Forms.Padding(2);
            this.txtDienThoai.MaxLength = 32767;
            this.txtDienThoai.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDienThoai.Modified = false;
            this.txtDienThoai.Multiline = false;
            this.txtDienThoai.Name = "txtDienThoai";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDienThoai.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDienThoai.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDienThoai.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.LightSeaGreen;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDienThoai.OnIdleState = stateProperties28;
            this.txtDienThoai.Padding = new System.Windows.Forms.Padding(2);
            this.txtDienThoai.PasswordChar = '\0';
            this.txtDienThoai.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDienThoai.PlaceholderText = "";
            this.txtDienThoai.ReadOnly = false;
            this.txtDienThoai.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDienThoai.SelectedText = "";
            this.txtDienThoai.SelectionLength = 0;
            this.txtDienThoai.SelectionStart = 0;
            this.txtDienThoai.ShortcutsEnabled = true;
            this.txtDienThoai.Size = new System.Drawing.Size(128, 31);
            this.txtDienThoai.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDienThoai.TabIndex = 40;
            this.txtDienThoai.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDienThoai.TextMarginBottom = 0;
            this.txtDienThoai.TextMarginLeft = 3;
            this.txtDienThoai.TextMarginTop = 0;
            this.txtDienThoai.TextPlaceholder = "";
            this.txtDienThoai.UseSystemPasswordChar = false;
            this.txtDienThoai.WordWrap = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.Black;
            this.label1.Location = new System.Drawing.Point(174, 17);
            this.label1.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(83, 15);
            this.label1.TabIndex = 39;
            this.label1.Text = "Số điện thoại:";
            // 
            // txtTenNCC
            // 
            this.txtTenNCC.AcceptsReturn = false;
            this.txtTenNCC.AcceptsTab = false;
            this.txtTenNCC.AnimationSpeed = 200;
            this.txtTenNCC.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTenNCC.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTenNCC.BackColor = System.Drawing.Color.Transparent;
            this.txtTenNCC.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTenNCC.BackgroundImage")));
            this.txtTenNCC.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTenNCC.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTenNCC.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTenNCC.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTenNCC.BorderRadius = 15;
            this.txtTenNCC.BorderThickness = 2;
            this.txtTenNCC.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTenNCC.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNCC.DefaultFont = new System.Drawing.Font("Arial", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTenNCC.DefaultText = "";
            this.txtTenNCC.FillColor = System.Drawing.Color.White;
            this.txtTenNCC.ForeColor = System.Drawing.Color.LightSeaGreen;
            this.txtTenNCC.HideSelection = true;
            this.txtTenNCC.IconLeft = null;
            this.txtTenNCC.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNCC.IconPadding = 10;
            this.txtTenNCC.IconRight = null;
            this.txtTenNCC.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenNCC.Lines = new string[0];
            this.txtTenNCC.Location = new System.Drawing.Point(9, 34);
            this.txtTenNCC.Margin = new System.Windows.Forms.Padding(2);
            this.txtTenNCC.MaxLength = 32767;
            this.txtTenNCC.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTenNCC.Modified = false;
            this.txtTenNCC.Multiline = false;
            this.txtTenNCC.Name = "txtTenNCC";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNCC.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTenNCC.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNCC.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.LightSeaGreen;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenNCC.OnIdleState = stateProperties32;
            this.txtTenNCC.Padding = new System.Windows.Forms.Padding(2);
            this.txtTenNCC.PasswordChar = '\0';
            this.txtTenNCC.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTenNCC.PlaceholderText = "";
            this.txtTenNCC.ReadOnly = false;
            this.txtTenNCC.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTenNCC.SelectedText = "";
            this.txtTenNCC.SelectionLength = 0;
            this.txtTenNCC.SelectionStart = 0;
            this.txtTenNCC.ShortcutsEnabled = true;
            this.txtTenNCC.Size = new System.Drawing.Size(133, 31);
            this.txtTenNCC.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTenNCC.TabIndex = 38;
            this.txtTenNCC.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTenNCC.TextMarginBottom = 0;
            this.txtTenNCC.TextMarginLeft = 3;
            this.txtTenNCC.TextMarginTop = 0;
            this.txtTenNCC.TextPlaceholder = "";
            this.txtTenNCC.UseSystemPasswordChar = false;
            this.txtTenNCC.WordWrap = true;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.Black;
            this.label3.Location = new System.Drawing.Point(7, 17);
            this.label3.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(110, 15);
            this.label3.TabIndex = 37;
            this.label3.Text = "Tên nhà cung cấp:";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(291, 15);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(322, 31);
            this.label4.TabIndex = 33;
            this.label4.Text = "Quản Lý Nhà Cung Cấp";
            // 
            // QuanLyNhaCungCap
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.ButtonHighlight;
            this.ClientSize = new System.Drawing.Size(811, 490);
            this.Controls.Add(this.tableLayoutPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "QuanLyNhaCungCap";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Quản lý nhà cung cấp";
            this.Load += new System.EventHandler(this.QuanLyNhaCungCap_Load);
            this.tableLayoutPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dtgNCC)).EndInit();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.bunifuGroupBox1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.GroupBox groupBox3;
        private Bunifu.UI.WinForms.BunifuTextBox txtSearchNCC;
        private Bunifu.UI.WinForms.BunifuDataGridView dtgNCC;
        private System.Windows.Forms.GroupBox groupBox2;
        private Bunifu.UI.WinForms.BunifuTextBox txtDiaChi;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox txtDienThoai;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txtTenNCC;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnThemNCC;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSuaNCC;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnXoaNCC;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private System.Windows.Forms.Label label4;
    }
}