namespace Smartphone_Management.GUI.BaoHanh
{
    partial class QuanLyBaoHanh
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(QuanLyBaoHanh));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle7 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle8 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle9 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle10 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle11 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle12 = new System.Windows.Forms.DataGridViewCellStyle();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.txtTrangThai = new Bunifu.UI.WinForms.BunifuDropdown();
            this.button1 = new System.Windows.Forms.Button();
            this.btnBhXoa = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnBhSua = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnbhThem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtThoiGianBaoHanh = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.bunifuGroupBox2 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.cbbMaSP = new Bunifu.UI.WinForms.BunifuDropdown();
            this.cbbMaBaoHanh = new Bunifu.UI.WinForms.BunifuDropdown();
            this.label4 = new System.Windows.Forms.Label();
            this.btnCtThem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCtXoa = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label5 = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuButton4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label1 = new System.Windows.Forms.Label();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.dataChiTiet = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.dataBaoHanh = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuGroupBox1.SuspendLayout();
            this.bunifuGroupBox2.SuspendLayout();
            this.panel1.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.tableLayoutPanel3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dataChiTiet)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataBaoHanh)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox1.BorderRadius = 1;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.txtTrangThai);
            this.bunifuGroupBox1.Controls.Add(this.button1);
            this.bunifuGroupBox1.Controls.Add(this.btnBhXoa);
            this.bunifuGroupBox1.Controls.Add(this.btnBhSua);
            this.bunifuGroupBox1.Controls.Add(this.btnbhThem);
            this.bunifuGroupBox1.Controls.Add(this.txtThoiGianBaoHanh);
            this.bunifuGroupBox1.Controls.Add(this.label3);
            this.bunifuGroupBox1.Controls.Add(this.label2);
            this.bunifuGroupBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(391, 3);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(383, 199);
            this.bunifuGroupBox1.TabIndex = 2;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "bunifuGroupBox1";
            this.bunifuGroupBox1.Enter += new System.EventHandler(this.bunifuGroupBox1_Enter);
            // 
            // txtTrangThai
            // 
            this.txtTrangThai.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.txtTrangThai.BackColor = System.Drawing.Color.Transparent;
            this.txtTrangThai.BackgroundColor = System.Drawing.Color.White;
            this.txtTrangThai.BorderColor = System.Drawing.Color.Silver;
            this.txtTrangThai.BorderRadius = 1;
            this.txtTrangThai.Color = System.Drawing.Color.Silver;
            this.txtTrangThai.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.txtTrangThai.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.txtTrangThai.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTrangThai.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.txtTrangThai.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.txtTrangThai.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.txtTrangThai.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.txtTrangThai.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.txtTrangThai.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.txtTrangThai.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.txtTrangThai.FillDropDown = true;
            this.txtTrangThai.FillIndicator = false;
            this.txtTrangThai.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.txtTrangThai.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtTrangThai.ForeColor = System.Drawing.Color.Black;
            this.txtTrangThai.FormattingEnabled = true;
            this.txtTrangThai.Icon = null;
            this.txtTrangThai.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.txtTrangThai.IndicatorColor = System.Drawing.Color.Gray;
            this.txtTrangThai.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.txtTrangThai.ItemBackColor = System.Drawing.Color.White;
            this.txtTrangThai.ItemBorderColor = System.Drawing.Color.White;
            this.txtTrangThai.ItemForeColor = System.Drawing.Color.Black;
            this.txtTrangThai.ItemHeight = 26;
            this.txtTrangThai.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.txtTrangThai.ItemHighLightForeColor = System.Drawing.Color.White;
            this.txtTrangThai.Items.AddRange(new object[] {
            "T",
            "F"});
            this.txtTrangThai.ItemTopMargin = 3;
            this.txtTrangThai.Location = new System.Drawing.Point(154, 69);
            this.txtTrangThai.Name = "txtTrangThai";
            this.txtTrangThai.Size = new System.Drawing.Size(179, 32);
            this.txtTrangThai.TabIndex = 0;
            this.txtTrangThai.Text = null;
            this.txtTrangThai.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.txtTrangThai.TextLeftMargin = 5;
            // 
            // button1
            // 
            this.button1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.button1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.button1.Image = global::Smartphone_Management.Properties.Resources.Refresh;
            this.button1.Location = new System.Drawing.Point(340, 22);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(37, 37);
            this.button1.TabIndex = 3;
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // btnBhXoa
            // 
            this.btnBhXoa.AllowAnimations = true;
            this.btnBhXoa.AllowMouseEffects = true;
            this.btnBhXoa.AllowToggling = false;
            this.btnBhXoa.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnBhXoa.AnimationSpeed = 200;
            this.btnBhXoa.AutoGenerateColors = false;
            this.btnBhXoa.AutoRoundBorders = false;
            this.btnBhXoa.AutoSizeLeftIcon = true;
            this.btnBhXoa.AutoSizeRightIcon = true;
            this.btnBhXoa.BackColor = System.Drawing.Color.Transparent;
            this.btnBhXoa.BackColor1 = System.Drawing.Color.Black;
            this.btnBhXoa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBhXoa.BackgroundImage")));
            this.btnBhXoa.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.btnBhXoa.ButtonText = "Xóa";
            this.btnBhXoa.ButtonTextMarginLeft = 0;
            this.btnBhXoa.ColorContrastOnClick = 45;
            this.btnBhXoa.ColorContrastOnHover = 45;
            this.btnBhXoa.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnBhXoa.CustomizableEdges = borderEdges7;
            this.btnBhXoa.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBhXoa.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBhXoa.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBhXoa.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBhXoa.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBhXoa.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBhXoa.ForeColor = System.Drawing.Color.White;
            this.btnBhXoa.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBhXoa.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBhXoa.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBhXoa.IconMarginLeft = 11;
            this.btnBhXoa.IconPadding = 10;
            this.btnBhXoa.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBhXoa.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBhXoa.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBhXoa.IconSize = 25;
            this.btnBhXoa.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnBhXoa.IdleBorderRadius = 35;
            this.btnBhXoa.IdleBorderThickness = 1;
            this.btnBhXoa.IdleFillColor = System.Drawing.Color.Black;
            this.btnBhXoa.IdleIconLeftImage = null;
            this.btnBhXoa.IdleIconRightImage = null;
            this.btnBhXoa.IndicateFocus = false;
            this.btnBhXoa.Location = new System.Drawing.Point(236, 148);
            this.btnBhXoa.Name = "btnBhXoa";
            this.btnBhXoa.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBhXoa.OnDisabledState.BorderRadius = 35;
            this.btnBhXoa.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBhXoa.OnDisabledState.BorderThickness = 1;
            this.btnBhXoa.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBhXoa.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBhXoa.OnDisabledState.IconLeftImage = null;
            this.btnBhXoa.OnDisabledState.IconRightImage = null;
            this.btnBhXoa.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnBhXoa.onHoverState.BorderRadius = 35;
            this.btnBhXoa.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBhXoa.onHoverState.BorderThickness = 1;
            this.btnBhXoa.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnBhXoa.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnBhXoa.onHoverState.IconLeftImage = null;
            this.btnBhXoa.onHoverState.IconRightImage = null;
            this.btnBhXoa.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnBhXoa.OnIdleState.BorderRadius = 35;
            this.btnBhXoa.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.btnBhXoa.OnIdleState.BorderThickness = 1;
            this.btnBhXoa.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnBhXoa.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnBhXoa.OnIdleState.IconLeftImage = null;
            this.btnBhXoa.OnIdleState.IconRightImage = null;
            this.btnBhXoa.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBhXoa.OnPressedState.BorderRadius = 35;
            this.btnBhXoa.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBhXoa.OnPressedState.BorderThickness = 1;
            this.btnBhXoa.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBhXoa.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBhXoa.OnPressedState.IconLeftImage = null;
            this.btnBhXoa.OnPressedState.IconRightImage = null;
            this.btnBhXoa.Size = new System.Drawing.Size(74, 39);
            this.btnBhXoa.TabIndex = 2;
            this.btnBhXoa.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBhXoa.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBhXoa.TextMarginLeft = 0;
            this.btnBhXoa.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBhXoa.UseDefaultRadiusAndThickness = true;
            this.btnBhXoa.Click += new System.EventHandler(this.btnBhXoa_Click);
            // 
            // btnBhSua
            // 
            this.btnBhSua.AllowAnimations = true;
            this.btnBhSua.AllowMouseEffects = true;
            this.btnBhSua.AllowToggling = false;
            this.btnBhSua.AnimationSpeed = 200;
            this.btnBhSua.AutoGenerateColors = false;
            this.btnBhSua.AutoRoundBorders = false;
            this.btnBhSua.AutoSizeLeftIcon = true;
            this.btnBhSua.AutoSizeRightIcon = true;
            this.btnBhSua.BackColor = System.Drawing.Color.Transparent;
            this.btnBhSua.BackColor1 = System.Drawing.Color.Black;
            this.btnBhSua.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBhSua.BackgroundImage")));
            this.btnBhSua.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.btnBhSua.ButtonText = "Sữa";
            this.btnBhSua.ButtonTextMarginLeft = 0;
            this.btnBhSua.ColorContrastOnClick = 45;
            this.btnBhSua.ColorContrastOnHover = 45;
            this.btnBhSua.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnBhSua.CustomizableEdges = borderEdges8;
            this.btnBhSua.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBhSua.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBhSua.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBhSua.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBhSua.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBhSua.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBhSua.ForeColor = System.Drawing.Color.White;
            this.btnBhSua.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBhSua.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBhSua.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBhSua.IconMarginLeft = 11;
            this.btnBhSua.IconPadding = 10;
            this.btnBhSua.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBhSua.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBhSua.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBhSua.IconSize = 25;
            this.btnBhSua.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnBhSua.IdleBorderRadius = 40;
            this.btnBhSua.IdleBorderThickness = 1;
            this.btnBhSua.IdleFillColor = System.Drawing.Color.Black;
            this.btnBhSua.IdleIconLeftImage = null;
            this.btnBhSua.IdleIconRightImage = null;
            this.btnBhSua.IndicateFocus = false;
            this.btnBhSua.Location = new System.Drawing.Point(115, 148);
            this.btnBhSua.Name = "btnBhSua";
            this.btnBhSua.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBhSua.OnDisabledState.BorderRadius = 40;
            this.btnBhSua.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBhSua.OnDisabledState.BorderThickness = 1;
            this.btnBhSua.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBhSua.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBhSua.OnDisabledState.IconLeftImage = null;
            this.btnBhSua.OnDisabledState.IconRightImage = null;
            this.btnBhSua.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnBhSua.onHoverState.BorderRadius = 40;
            this.btnBhSua.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBhSua.onHoverState.BorderThickness = 1;
            this.btnBhSua.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnBhSua.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnBhSua.onHoverState.IconLeftImage = null;
            this.btnBhSua.onHoverState.IconRightImage = null;
            this.btnBhSua.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnBhSua.OnIdleState.BorderRadius = 40;
            this.btnBhSua.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.btnBhSua.OnIdleState.BorderThickness = 1;
            this.btnBhSua.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnBhSua.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnBhSua.OnIdleState.IconLeftImage = null;
            this.btnBhSua.OnIdleState.IconRightImage = null;
            this.btnBhSua.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBhSua.OnPressedState.BorderRadius = 40;
            this.btnBhSua.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBhSua.OnPressedState.BorderThickness = 1;
            this.btnBhSua.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBhSua.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBhSua.OnPressedState.IconLeftImage = null;
            this.btnBhSua.OnPressedState.IconRightImage = null;
            this.btnBhSua.Size = new System.Drawing.Size(72, 39);
            this.btnBhSua.TabIndex = 2;
            this.btnBhSua.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBhSua.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBhSua.TextMarginLeft = 0;
            this.btnBhSua.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBhSua.UseDefaultRadiusAndThickness = true;
            this.btnBhSua.Click += new System.EventHandler(this.btnBhSua_Click);
            // 
            // btnbhThem
            // 
            this.btnbhThem.AllowAnimations = true;
            this.btnbhThem.AllowMouseEffects = true;
            this.btnbhThem.AllowToggling = false;
            this.btnbhThem.AnimationSpeed = 200;
            this.btnbhThem.AutoGenerateColors = false;
            this.btnbhThem.AutoRoundBorders = false;
            this.btnbhThem.AutoSizeLeftIcon = true;
            this.btnbhThem.AutoSizeRightIcon = true;
            this.btnbhThem.BackColor = System.Drawing.Color.Transparent;
            this.btnbhThem.BackColor1 = System.Drawing.Color.Black;
            this.btnbhThem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnbhThem.BackgroundImage")));
            this.btnbhThem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.btnbhThem.ButtonText = "Thêm";
            this.btnbhThem.ButtonTextMarginLeft = 0;
            this.btnbhThem.ColorContrastOnClick = 45;
            this.btnbhThem.ColorContrastOnHover = 45;
            this.btnbhThem.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnbhThem.CustomizableEdges = borderEdges9;
            this.btnbhThem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnbhThem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnbhThem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnbhThem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnbhThem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnbhThem.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnbhThem.ForeColor = System.Drawing.Color.White;
            this.btnbhThem.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnbhThem.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnbhThem.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnbhThem.IconMarginLeft = 11;
            this.btnbhThem.IconPadding = 10;
            this.btnbhThem.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnbhThem.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnbhThem.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnbhThem.IconSize = 25;
            this.btnbhThem.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnbhThem.IdleBorderRadius = 35;
            this.btnbhThem.IdleBorderThickness = 1;
            this.btnbhThem.IdleFillColor = System.Drawing.Color.Black;
            this.btnbhThem.IdleIconLeftImage = null;
            this.btnbhThem.IdleIconRightImage = null;
            this.btnbhThem.IndicateFocus = false;
            this.btnbhThem.Location = new System.Drawing.Point(9, 148);
            this.btnbhThem.Name = "btnbhThem";
            this.btnbhThem.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnbhThem.OnDisabledState.BorderRadius = 35;
            this.btnbhThem.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnbhThem.OnDisabledState.BorderThickness = 1;
            this.btnbhThem.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnbhThem.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnbhThem.OnDisabledState.IconLeftImage = null;
            this.btnbhThem.OnDisabledState.IconRightImage = null;
            this.btnbhThem.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnbhThem.onHoverState.BorderRadius = 35;
            this.btnbhThem.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnbhThem.onHoverState.BorderThickness = 1;
            this.btnbhThem.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnbhThem.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnbhThem.onHoverState.IconLeftImage = null;
            this.btnbhThem.onHoverState.IconRightImage = null;
            this.btnbhThem.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnbhThem.OnIdleState.BorderRadius = 35;
            this.btnbhThem.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.btnbhThem.OnIdleState.BorderThickness = 1;
            this.btnbhThem.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnbhThem.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnbhThem.OnIdleState.IconLeftImage = null;
            this.btnbhThem.OnIdleState.IconRightImage = null;
            this.btnbhThem.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnbhThem.OnPressedState.BorderRadius = 35;
            this.btnbhThem.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnbhThem.OnPressedState.BorderThickness = 1;
            this.btnbhThem.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnbhThem.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnbhThem.OnPressedState.IconLeftImage = null;
            this.btnbhThem.OnPressedState.IconRightImage = null;
            this.btnbhThem.Size = new System.Drawing.Size(71, 39);
            this.btnbhThem.TabIndex = 2;
            this.btnbhThem.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnbhThem.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnbhThem.TextMarginLeft = 0;
            this.btnbhThem.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnbhThem.UseDefaultRadiusAndThickness = true;
            this.btnbhThem.Click += new System.EventHandler(this.btnbhThem_Click);
            // 
            // txtThoiGianBaoHanh
            // 
            this.txtThoiGianBaoHanh.AcceptsReturn = false;
            this.txtThoiGianBaoHanh.AcceptsTab = false;
            this.txtThoiGianBaoHanh.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.txtThoiGianBaoHanh.AnimationSpeed = 200;
            this.txtThoiGianBaoHanh.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtThoiGianBaoHanh.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtThoiGianBaoHanh.BackColor = System.Drawing.Color.Transparent;
            this.txtThoiGianBaoHanh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtThoiGianBaoHanh.BackgroundImage")));
            this.txtThoiGianBaoHanh.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtThoiGianBaoHanh.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtThoiGianBaoHanh.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtThoiGianBaoHanh.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtThoiGianBaoHanh.BorderRadius = 1;
            this.txtThoiGianBaoHanh.BorderThickness = 1;
            this.txtThoiGianBaoHanh.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtThoiGianBaoHanh.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtThoiGianBaoHanh.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtThoiGianBaoHanh.DefaultText = "";
            this.txtThoiGianBaoHanh.FillColor = System.Drawing.Color.White;
            this.txtThoiGianBaoHanh.HideSelection = true;
            this.txtThoiGianBaoHanh.IconLeft = null;
            this.txtThoiGianBaoHanh.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtThoiGianBaoHanh.IconPadding = 10;
            this.txtThoiGianBaoHanh.IconRight = null;
            this.txtThoiGianBaoHanh.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtThoiGianBaoHanh.Lines = new string[0];
            this.txtThoiGianBaoHanh.Location = new System.Drawing.Point(154, 22);
            this.txtThoiGianBaoHanh.MaxLength = 32767;
            this.txtThoiGianBaoHanh.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtThoiGianBaoHanh.Modified = false;
            this.txtThoiGianBaoHanh.Multiline = false;
            this.txtThoiGianBaoHanh.Name = "txtThoiGianBaoHanh";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtThoiGianBaoHanh.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtThoiGianBaoHanh.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtThoiGianBaoHanh.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtThoiGianBaoHanh.OnIdleState = stateProperties8;
            this.txtThoiGianBaoHanh.Padding = new System.Windows.Forms.Padding(3);
            this.txtThoiGianBaoHanh.PasswordChar = '\0';
            this.txtThoiGianBaoHanh.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtThoiGianBaoHanh.PlaceholderText = "Enter text";
            this.txtThoiGianBaoHanh.ReadOnly = false;
            this.txtThoiGianBaoHanh.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtThoiGianBaoHanh.SelectedText = "";
            this.txtThoiGianBaoHanh.SelectionLength = 0;
            this.txtThoiGianBaoHanh.SelectionStart = 0;
            this.txtThoiGianBaoHanh.ShortcutsEnabled = true;
            this.txtThoiGianBaoHanh.Size = new System.Drawing.Size(179, 37);
            this.txtThoiGianBaoHanh.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtThoiGianBaoHanh.TabIndex = 1;
            this.txtThoiGianBaoHanh.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtThoiGianBaoHanh.TextMarginBottom = 0;
            this.txtThoiGianBaoHanh.TextMarginLeft = 3;
            this.txtThoiGianBaoHanh.TextMarginTop = 0;
            this.txtThoiGianBaoHanh.TextPlaceholder = "Enter text";
            this.txtThoiGianBaoHanh.UseSystemPasswordChar = false;
            this.txtThoiGianBaoHanh.WordWrap = true;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.SystemColors.Control;
            this.label3.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.Black;
            this.label3.Location = new System.Drawing.Point(6, 70);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(74, 17);
            this.label3.TabIndex = 0;
            this.label3.Text = "Trạng Thái";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.SystemColors.Control;
            this.label2.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.Black;
            this.label2.Location = new System.Drawing.Point(6, 33);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(132, 17);
            this.label2.TabIndex = 0;
            this.label2.Text = "Thời Gian Bảo Hành";
            // 
            // bunifuGroupBox2
            // 
            this.bunifuGroupBox2.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox2.BorderRadius = 1;
            this.bunifuGroupBox2.BorderThickness = 1;
            this.bunifuGroupBox2.Controls.Add(this.cbbMaSP);
            this.bunifuGroupBox2.Controls.Add(this.cbbMaBaoHanh);
            this.bunifuGroupBox2.Controls.Add(this.label4);
            this.bunifuGroupBox2.Controls.Add(this.btnCtThem);
            this.bunifuGroupBox2.Controls.Add(this.btnCtXoa);
            this.bunifuGroupBox2.Controls.Add(this.label5);
            this.bunifuGroupBox2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuGroupBox2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuGroupBox2.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox2.LabelIndent = 10;
            this.bunifuGroupBox2.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox2.Location = new System.Drawing.Point(3, 3);
            this.bunifuGroupBox2.Name = "bunifuGroupBox2";
            this.bunifuGroupBox2.Size = new System.Drawing.Size(382, 199);
            this.bunifuGroupBox2.TabIndex = 2;
            this.bunifuGroupBox2.TabStop = false;
            this.bunifuGroupBox2.Text = "bunifuGroupBox1";
            this.bunifuGroupBox2.Enter += new System.EventHandler(this.bunifuGroupBox2_Enter);
            // 
            // cbbMaSP
            // 
            this.cbbMaSP.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.cbbMaSP.BackColor = System.Drawing.Color.Transparent;
            this.cbbMaSP.BackgroundColor = System.Drawing.Color.White;
            this.cbbMaSP.BorderColor = System.Drawing.Color.Silver;
            this.cbbMaSP.BorderRadius = 1;
            this.cbbMaSP.Color = System.Drawing.Color.Silver;
            this.cbbMaSP.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbbMaSP.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbbMaSP.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbbMaSP.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbbMaSP.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbbMaSP.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbbMaSP.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbbMaSP.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbbMaSP.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbbMaSP.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbbMaSP.FillDropDown = true;
            this.cbbMaSP.FillIndicator = false;
            this.cbbMaSP.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbbMaSP.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cbbMaSP.ForeColor = System.Drawing.Color.Black;
            this.cbbMaSP.FormattingEnabled = true;
            this.cbbMaSP.Icon = null;
            this.cbbMaSP.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbbMaSP.IndicatorColor = System.Drawing.Color.Gray;
            this.cbbMaSP.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbbMaSP.ItemBackColor = System.Drawing.Color.White;
            this.cbbMaSP.ItemBorderColor = System.Drawing.Color.White;
            this.cbbMaSP.ItemForeColor = System.Drawing.Color.Black;
            this.cbbMaSP.ItemHeight = 26;
            this.cbbMaSP.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cbbMaSP.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbbMaSP.ItemTopMargin = 3;
            this.cbbMaSP.Location = new System.Drawing.Point(162, 65);
            this.cbbMaSP.Name = "cbbMaSP";
            this.cbbMaSP.Size = new System.Drawing.Size(194, 32);
            this.cbbMaSP.TabIndex = 0;
            this.cbbMaSP.Text = null;
            this.cbbMaSP.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbbMaSP.TextLeftMargin = 5;
            // 
            // cbbMaBaoHanh
            // 
            this.cbbMaBaoHanh.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.cbbMaBaoHanh.BackColor = System.Drawing.Color.Transparent;
            this.cbbMaBaoHanh.BackgroundColor = System.Drawing.Color.White;
            this.cbbMaBaoHanh.BorderColor = System.Drawing.Color.Silver;
            this.cbbMaBaoHanh.BorderRadius = 1;
            this.cbbMaBaoHanh.Color = System.Drawing.Color.Silver;
            this.cbbMaBaoHanh.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbbMaBaoHanh.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbbMaBaoHanh.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbbMaBaoHanh.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbbMaBaoHanh.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbbMaBaoHanh.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbbMaBaoHanh.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbbMaBaoHanh.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbbMaBaoHanh.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbbMaBaoHanh.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbbMaBaoHanh.FillDropDown = true;
            this.cbbMaBaoHanh.FillIndicator = false;
            this.cbbMaBaoHanh.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbbMaBaoHanh.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cbbMaBaoHanh.ForeColor = System.Drawing.Color.Black;
            this.cbbMaBaoHanh.FormattingEnabled = true;
            this.cbbMaBaoHanh.Icon = null;
            this.cbbMaBaoHanh.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbbMaBaoHanh.IndicatorColor = System.Drawing.Color.Gray;
            this.cbbMaBaoHanh.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbbMaBaoHanh.ItemBackColor = System.Drawing.Color.White;
            this.cbbMaBaoHanh.ItemBorderColor = System.Drawing.Color.White;
            this.cbbMaBaoHanh.ItemForeColor = System.Drawing.Color.Black;
            this.cbbMaBaoHanh.ItemHeight = 26;
            this.cbbMaBaoHanh.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cbbMaBaoHanh.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbbMaBaoHanh.ItemTopMargin = 3;
            this.cbbMaBaoHanh.Location = new System.Drawing.Point(162, 27);
            this.cbbMaBaoHanh.Name = "cbbMaBaoHanh";
            this.cbbMaBaoHanh.Size = new System.Drawing.Size(194, 32);
            this.cbbMaBaoHanh.TabIndex = 0;
            this.cbbMaBaoHanh.Text = null;
            this.cbbMaBaoHanh.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbbMaBaoHanh.TextLeftMargin = 5;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.SystemColors.Control;
            this.label4.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.Black;
            this.label4.Location = new System.Drawing.Point(6, 33);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(91, 17);
            this.label4.TabIndex = 0;
            this.label4.Text = "Mã Bảo Hành";
            // 
            // btnCtThem
            // 
            this.btnCtThem.AllowAnimations = true;
            this.btnCtThem.AllowMouseEffects = true;
            this.btnCtThem.AllowToggling = false;
            this.btnCtThem.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnCtThem.AnimationSpeed = 200;
            this.btnCtThem.AutoGenerateColors = false;
            this.btnCtThem.AutoRoundBorders = false;
            this.btnCtThem.AutoSizeLeftIcon = true;
            this.btnCtThem.AutoSizeRightIcon = true;
            this.btnCtThem.BackColor = System.Drawing.Color.Transparent;
            this.btnCtThem.BackColor1 = System.Drawing.Color.Black;
            this.btnCtThem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCtThem.BackgroundImage")));
            this.btnCtThem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.btnCtThem.ButtonText = "Thêm";
            this.btnCtThem.ButtonTextMarginLeft = 0;
            this.btnCtThem.ColorContrastOnClick = 45;
            this.btnCtThem.ColorContrastOnHover = 45;
            this.btnCtThem.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.btnCtThem.CustomizableEdges = borderEdges10;
            this.btnCtThem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCtThem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCtThem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCtThem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCtThem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCtThem.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCtThem.ForeColor = System.Drawing.Color.White;
            this.btnCtThem.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCtThem.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCtThem.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCtThem.IconMarginLeft = 11;
            this.btnCtThem.IconPadding = 10;
            this.btnCtThem.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCtThem.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCtThem.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCtThem.IconSize = 25;
            this.btnCtThem.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCtThem.IdleBorderRadius = 35;
            this.btnCtThem.IdleBorderThickness = 1;
            this.btnCtThem.IdleFillColor = System.Drawing.Color.Black;
            this.btnCtThem.IdleIconLeftImage = null;
            this.btnCtThem.IdleIconRightImage = null;
            this.btnCtThem.IndicateFocus = false;
            this.btnCtThem.Location = new System.Drawing.Point(236, 148);
            this.btnCtThem.Name = "btnCtThem";
            this.btnCtThem.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCtThem.OnDisabledState.BorderRadius = 35;
            this.btnCtThem.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCtThem.OnDisabledState.BorderThickness = 1;
            this.btnCtThem.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCtThem.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCtThem.OnDisabledState.IconLeftImage = null;
            this.btnCtThem.OnDisabledState.IconRightImage = null;
            this.btnCtThem.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCtThem.onHoverState.BorderRadius = 35;
            this.btnCtThem.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCtThem.onHoverState.BorderThickness = 1;
            this.btnCtThem.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCtThem.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCtThem.onHoverState.IconLeftImage = null;
            this.btnCtThem.onHoverState.IconRightImage = null;
            this.btnCtThem.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCtThem.OnIdleState.BorderRadius = 35;
            this.btnCtThem.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.btnCtThem.OnIdleState.BorderThickness = 1;
            this.btnCtThem.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnCtThem.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCtThem.OnIdleState.IconLeftImage = null;
            this.btnCtThem.OnIdleState.IconRightImage = null;
            this.btnCtThem.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCtThem.OnPressedState.BorderRadius = 35;
            this.btnCtThem.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCtThem.OnPressedState.BorderThickness = 1;
            this.btnCtThem.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCtThem.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCtThem.OnPressedState.IconLeftImage = null;
            this.btnCtThem.OnPressedState.IconRightImage = null;
            this.btnCtThem.Size = new System.Drawing.Size(57, 39);
            this.btnCtThem.TabIndex = 2;
            this.btnCtThem.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCtThem.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCtThem.TextMarginLeft = 0;
            this.btnCtThem.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCtThem.UseDefaultRadiusAndThickness = true;
            this.btnCtThem.Click += new System.EventHandler(this.btnCtThem_Click);
            // 
            // btnCtXoa
            // 
            this.btnCtXoa.AllowAnimations = true;
            this.btnCtXoa.AllowMouseEffects = true;
            this.btnCtXoa.AllowToggling = false;
            this.btnCtXoa.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnCtXoa.AnimationSpeed = 200;
            this.btnCtXoa.AutoGenerateColors = false;
            this.btnCtXoa.AutoRoundBorders = false;
            this.btnCtXoa.AutoSizeLeftIcon = true;
            this.btnCtXoa.AutoSizeRightIcon = true;
            this.btnCtXoa.BackColor = System.Drawing.Color.Transparent;
            this.btnCtXoa.BackColor1 = System.Drawing.Color.Black;
            this.btnCtXoa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCtXoa.BackgroundImage")));
            this.btnCtXoa.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.btnCtXoa.ButtonText = "Xóa";
            this.btnCtXoa.ButtonTextMarginLeft = 0;
            this.btnCtXoa.ColorContrastOnClick = 45;
            this.btnCtXoa.ColorContrastOnHover = 45;
            this.btnCtXoa.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.btnCtXoa.CustomizableEdges = borderEdges11;
            this.btnCtXoa.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCtXoa.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCtXoa.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCtXoa.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCtXoa.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCtXoa.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCtXoa.ForeColor = System.Drawing.Color.White;
            this.btnCtXoa.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCtXoa.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCtXoa.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCtXoa.IconMarginLeft = 11;
            this.btnCtXoa.IconPadding = 10;
            this.btnCtXoa.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCtXoa.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCtXoa.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCtXoa.IconSize = 25;
            this.btnCtXoa.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCtXoa.IdleBorderRadius = 35;
            this.btnCtXoa.IdleBorderThickness = 1;
            this.btnCtXoa.IdleFillColor = System.Drawing.Color.Black;
            this.btnCtXoa.IdleIconLeftImage = null;
            this.btnCtXoa.IdleIconRightImage = null;
            this.btnCtXoa.IndicateFocus = false;
            this.btnCtXoa.Location = new System.Drawing.Point(310, 148);
            this.btnCtXoa.Name = "btnCtXoa";
            this.btnCtXoa.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCtXoa.OnDisabledState.BorderRadius = 35;
            this.btnCtXoa.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCtXoa.OnDisabledState.BorderThickness = 1;
            this.btnCtXoa.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCtXoa.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCtXoa.OnDisabledState.IconLeftImage = null;
            this.btnCtXoa.OnDisabledState.IconRightImage = null;
            this.btnCtXoa.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCtXoa.onHoverState.BorderRadius = 35;
            this.btnCtXoa.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCtXoa.onHoverState.BorderThickness = 1;
            this.btnCtXoa.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCtXoa.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCtXoa.onHoverState.IconLeftImage = null;
            this.btnCtXoa.onHoverState.IconRightImage = null;
            this.btnCtXoa.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCtXoa.OnIdleState.BorderRadius = 35;
            this.btnCtXoa.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
            this.btnCtXoa.OnIdleState.BorderThickness = 1;
            this.btnCtXoa.OnIdleState.FillColor = System.Drawing.Color.Black;
            this.btnCtXoa.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCtXoa.OnIdleState.IconLeftImage = null;
            this.btnCtXoa.OnIdleState.IconRightImage = null;
            this.btnCtXoa.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCtXoa.OnPressedState.BorderRadius = 35;
            this.btnCtXoa.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCtXoa.OnPressedState.BorderThickness = 1;
            this.btnCtXoa.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCtXoa.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCtXoa.OnPressedState.IconLeftImage = null;
            this.btnCtXoa.OnPressedState.IconRightImage = null;
            this.btnCtXoa.Size = new System.Drawing.Size(46, 39);
            this.btnCtXoa.TabIndex = 2;
            this.btnCtXoa.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCtXoa.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCtXoa.TextMarginLeft = 0;
            this.btnCtXoa.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCtXoa.UseDefaultRadiusAndThickness = true;
            this.btnCtXoa.Click += new System.EventHandler(this.btnCtXoa_Click);
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.SystemColors.Control;
            this.label5.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.Black;
            this.label5.Location = new System.Drawing.Point(6, 70);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(69, 17);
            this.label5.TabIndex = 0;
            this.label5.Text = "Sản Phẩm";
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.bunifuButton4);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(783, 49);
            this.panel1.TabIndex = 3;
            // 
            // bunifuButton4
            // 
            this.bunifuButton4.AllowAnimations = true;
            this.bunifuButton4.AllowMouseEffects = true;
            this.bunifuButton4.AllowToggling = false;
            this.bunifuButton4.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuButton4.AnimationSpeed = 200;
            this.bunifuButton4.AutoGenerateColors = false;
            this.bunifuButton4.AutoRoundBorders = false;
            this.bunifuButton4.AutoSizeLeftIcon = true;
            this.bunifuButton4.AutoSizeRightIcon = true;
            this.bunifuButton4.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton4.BackgroundImage")));
            this.bunifuButton4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.ButtonText = "Thông Tin Bảo Hành";
            this.bunifuButton4.ButtonTextMarginLeft = 0;
            this.bunifuButton4.ColorContrastOnClick = 45;
            this.bunifuButton4.ColorContrastOnHover = 45;
            this.bunifuButton4.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.bunifuButton4.CustomizableEdges = borderEdges12;
            this.bunifuButton4.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton4.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton4.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton4.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton4.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton4.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton4.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton4.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton4.IconMarginLeft = 11;
            this.bunifuButton4.IconPadding = 10;
            this.bunifuButton4.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton4.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton4.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton4.IconSize = 25;
            this.bunifuButton4.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton4.IdleBorderRadius = 1;
            this.bunifuButton4.IdleBorderThickness = 1;
            this.bunifuButton4.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton4.IdleIconLeftImage = null;
            this.bunifuButton4.IdleIconRightImage = null;
            this.bunifuButton4.IndicateFocus = false;
            this.bunifuButton4.Location = new System.Drawing.Point(616, 3);
            this.bunifuButton4.Name = "bunifuButton4";
            this.bunifuButton4.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton4.OnDisabledState.BorderRadius = 1;
            this.bunifuButton4.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnDisabledState.BorderThickness = 1;
            this.bunifuButton4.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton4.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton4.OnDisabledState.IconLeftImage = null;
            this.bunifuButton4.OnDisabledState.IconRightImage = null;
            this.bunifuButton4.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton4.onHoverState.BorderRadius = 1;
            this.bunifuButton4.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.onHoverState.BorderThickness = 1;
            this.bunifuButton4.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton4.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.onHoverState.IconLeftImage = null;
            this.bunifuButton4.onHoverState.IconRightImage = null;
            this.bunifuButton4.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton4.OnIdleState.BorderRadius = 1;
            this.bunifuButton4.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnIdleState.BorderThickness = 1;
            this.bunifuButton4.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton4.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.OnIdleState.IconLeftImage = null;
            this.bunifuButton4.OnIdleState.IconRightImage = null;
            this.bunifuButton4.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton4.OnPressedState.BorderRadius = 1;
            this.bunifuButton4.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnPressedState.BorderThickness = 1;
            this.bunifuButton4.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton4.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.OnPressedState.IconLeftImage = null;
            this.bunifuButton4.OnPressedState.IconRightImage = null;
            this.bunifuButton4.Size = new System.Drawing.Size(130, 25);
            this.bunifuButton4.TabIndex = 1;
            this.bunifuButton4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton4.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton4.TextMarginLeft = 0;
            this.bunifuButton4.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton4.UseDefaultRadiusAndThickness = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.Black;
            this.label1.Location = new System.Drawing.Point(13, 4);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(210, 25);
            this.label1.TabIndex = 0;
            this.label1.Text = "Quản Lý Bảo Hành";
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 1;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel2, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel3, 0, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 49);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 2;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 46.4467F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 53.5533F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(783, 394);
            this.tableLayoutPanel1.TabIndex = 4;
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.ColumnCount = 2;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.Controls.Add(this.bunifuGroupBox2, 0, 0);
            this.tableLayoutPanel2.Controls.Add(this.bunifuGroupBox1, 1, 0);
            this.tableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel2.Location = new System.Drawing.Point(3, 186);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 1;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(777, 205);
            this.tableLayoutPanel2.TabIndex = 0;
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.ColumnCount = 2;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.Controls.Add(this.dataChiTiet, 0, 0);
            this.tableLayoutPanel3.Controls.Add(this.dataBaoHanh, 1, 0);
            this.tableLayoutPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel3.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 1;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(777, 177);
            this.tableLayoutPanel3.TabIndex = 1;
            // 
            // dataChiTiet
            // 
            this.dataChiTiet.AllowCustomTheming = false;
            dataGridViewCellStyle7.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(203)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))));
            dataGridViewCellStyle7.ForeColor = System.Drawing.Color.Black;
            this.dataChiTiet.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle7;
            this.dataChiTiet.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dataChiTiet.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataChiTiet.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataChiTiet.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle8.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle8.BackColor = System.Drawing.Color.DarkSlateGray;
            dataGridViewCellStyle8.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle8.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle8.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(63)))), ((int)(((byte)(63)))));
            dataGridViewCellStyle8.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle8.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataChiTiet.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle8;
            this.dataChiTiet.ColumnHeadersHeight = 40;
            this.dataChiTiet.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(203)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))));
            this.dataChiTiet.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataChiTiet.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataChiTiet.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(130)))), ((int)(((byte)(149)))), ((int)(((byte)(149)))));
            this.dataChiTiet.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dataChiTiet.CurrentTheme.BackColor = System.Drawing.Color.DarkSlateGray;
            this.dataChiTiet.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(202)))), ((int)(((byte)(202)))));
            this.dataChiTiet.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DarkSlateGray;
            this.dataChiTiet.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dataChiTiet.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dataChiTiet.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(63)))), ((int)(((byte)(63)))));
            this.dataChiTiet.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dataChiTiet.CurrentTheme.Name = null;
            this.dataChiTiet.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(219)))), ((int)(((byte)(219)))));
            this.dataChiTiet.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataChiTiet.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataChiTiet.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(130)))), ((int)(((byte)(149)))), ((int)(((byte)(149)))));
            this.dataChiTiet.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle9.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle9.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(219)))), ((int)(((byte)(219)))));
            dataGridViewCellStyle9.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle9.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle9.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(130)))), ((int)(((byte)(149)))), ((int)(((byte)(149)))));
            dataGridViewCellStyle9.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle9.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataChiTiet.DefaultCellStyle = dataGridViewCellStyle9;
            this.dataChiTiet.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataChiTiet.EnableHeadersVisualStyles = false;
            this.dataChiTiet.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(202)))), ((int)(((byte)(202)))));
            this.dataChiTiet.HeaderBackColor = System.Drawing.Color.DarkSlateGray;
            this.dataChiTiet.HeaderBgColor = System.Drawing.Color.Empty;
            this.dataChiTiet.HeaderForeColor = System.Drawing.Color.White;
            this.dataChiTiet.Location = new System.Drawing.Point(3, 3);
            this.dataChiTiet.MultiSelect = false;
            this.dataChiTiet.Name = "dataChiTiet";
            this.dataChiTiet.ReadOnly = true;
            this.dataChiTiet.RowHeadersVisible = false;
            this.dataChiTiet.RowTemplate.Height = 40;
            this.dataChiTiet.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataChiTiet.Size = new System.Drawing.Size(382, 171);
            this.dataChiTiet.TabIndex = 0;
            this.dataChiTiet.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.DarkSlateGray;
            // 
            // dataBaoHanh
            // 
            this.dataBaoHanh.AllowCustomTheming = false;
            dataGridViewCellStyle10.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(203)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))));
            dataGridViewCellStyle10.ForeColor = System.Drawing.Color.Black;
            this.dataBaoHanh.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle10;
            this.dataBaoHanh.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dataBaoHanh.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataBaoHanh.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataBaoHanh.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle11.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle11.BackColor = System.Drawing.Color.DarkSlateGray;
            dataGridViewCellStyle11.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle11.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle11.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(63)))), ((int)(((byte)(63)))));
            dataGridViewCellStyle11.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle11.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataBaoHanh.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle11;
            this.dataBaoHanh.ColumnHeadersHeight = 40;
            this.dataBaoHanh.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(203)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))));
            this.dataBaoHanh.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataBaoHanh.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataBaoHanh.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(130)))), ((int)(((byte)(149)))), ((int)(((byte)(149)))));
            this.dataBaoHanh.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dataBaoHanh.CurrentTheme.BackColor = System.Drawing.Color.DarkSlateGray;
            this.dataBaoHanh.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(202)))), ((int)(((byte)(202)))));
            this.dataBaoHanh.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DarkSlateGray;
            this.dataBaoHanh.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dataBaoHanh.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dataBaoHanh.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(63)))), ((int)(((byte)(63)))));
            this.dataBaoHanh.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dataBaoHanh.CurrentTheme.Name = null;
            this.dataBaoHanh.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(219)))), ((int)(((byte)(219)))));
            this.dataBaoHanh.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataBaoHanh.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataBaoHanh.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(130)))), ((int)(((byte)(149)))), ((int)(((byte)(149)))));
            this.dataBaoHanh.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle12.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle12.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(219)))), ((int)(((byte)(219)))));
            dataGridViewCellStyle12.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle12.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle12.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(130)))), ((int)(((byte)(149)))), ((int)(((byte)(149)))));
            dataGridViewCellStyle12.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle12.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataBaoHanh.DefaultCellStyle = dataGridViewCellStyle12;
            this.dataBaoHanh.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dataBaoHanh.EnableHeadersVisualStyles = false;
            this.dataBaoHanh.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(202)))), ((int)(((byte)(202)))));
            this.dataBaoHanh.HeaderBackColor = System.Drawing.Color.DarkSlateGray;
            this.dataBaoHanh.HeaderBgColor = System.Drawing.Color.Empty;
            this.dataBaoHanh.HeaderForeColor = System.Drawing.Color.White;
            this.dataBaoHanh.Location = new System.Drawing.Point(391, 3);
            this.dataBaoHanh.MultiSelect = false;
            this.dataBaoHanh.Name = "dataBaoHanh";
            this.dataBaoHanh.ReadOnly = true;
            this.dataBaoHanh.RowHeadersVisible = false;
            this.dataBaoHanh.RowTemplate.Height = 40;
            this.dataBaoHanh.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataBaoHanh.Size = new System.Drawing.Size(383, 171);
            this.dataBaoHanh.TabIndex = 0;
            this.dataBaoHanh.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.DarkSlateGray;
            this.dataBaoHanh.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dataBaoHanh_CellContentClick_1);
            this.dataBaoHanh.CellMouseClick += new System.Windows.Forms.DataGridViewCellMouseEventHandler(this.dataBaoHanh_CellMouseClick);
            // 
            // QuanLyBaoHanh
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(783, 444);
            this.Controls.Add(this.tableLayoutPanel1);
            this.Controls.Add(this.panel1);
            this.Name = "QuanLyBaoHanh";
            this.Text = "QuanLyBaoHanh";
            this.Load += new System.EventHandler(this.QuanLyBaoHanh_Load);
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox1.PerformLayout();
            this.bunifuGroupBox2.ResumeLayout(false);
            this.bunifuGroupBox2.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel2.ResumeLayout(false);
            this.tableLayoutPanel3.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dataChiTiet)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dataBaoHanh)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox2;
        private Bunifu.UI.WinForms.BunifuTextBox txtThoiGianBaoHanh;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBhXoa;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBhSua;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnbhThem;
        private Bunifu.UI.WinForms.BunifuDropdown cbbMaSP;
        private Bunifu.UI.WinForms.BunifuDropdown cbbMaBaoHanh;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCtThem;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCtXoa;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        private Bunifu.UI.WinForms.BunifuDataGridView dataChiTiet;
        private Bunifu.UI.WinForms.BunifuDataGridView dataBaoHanh;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton4;
        private System.Windows.Forms.Button button1;
        private Bunifu.UI.WinForms.BunifuDropdown txtTrangThai;
    }
}